env:
  browser: true
  es2020: true
extends:
  - google
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    './tsconfig.json'
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
